### ISSUE TITLE
Fatal Error: 'Supplier Not Found' in 'surveilr udi pgp' [version: alpha v0.15.4]

### ISSUE THREAD

**Issue by Niba-nazar** [opsfolio/resource-surveillance#100]
Hi,

For "local, remote, and atc-mode," we have tested "surveilr udi pgp." It functions exactly as it intended. However, the following error was encountered when testing "surveilr udi pgp" using the config-full.ncl file:

```bash

$ surveilr udi pgp -c ./config-full.ncl
2024-02-09T10:49:51.955351Z  INFO udi_pgp:130: UDI PGP SQLD listening on 127.0.0.1:7755
2024-02-09T10:49:51.955388Z  INFO udi_pgp::health:21: Health server is binding on 127.0.0.1:3155

-------------------

$ psql -h 127.0.0.1 -p 7755 -U opsfolio -d "supplier-one" -c "SELECT cpu_type, cpu_brand, hardware_vendor, h
ardware_model FROM system_info"
FATAL:  Supplier not found. Got: supplier-one

```
Seems like, an updated config.ncl file which includes all the suppliers along with the username and password is needed.

**Comment by Lilit0x** [comment]
Hi there.
The `config-full.ncl` file does not contain any supplier, that is if you're using the one [here](https://github.com/Lilit0x/resource-surveillance/blob/feat/udi/support/config-full.ncl). That means there is no supplier to connect to and you can just connect to UDI-PGP without any username or password. You don't necessarily have to start UDI-PGP with an empty supplier list, you can add them all at the beginning and then update it as you wish.

As I mentioned, please check this [resource](https://github.com/Lilit0x/resource-surveillance/blob/feat/udi/support/test-e2e.sql) as it contains a step-by-step guide, albeit, with VSCode SQL Notebook. I will add the corresponding `psql` commands there too to follow along.

**Comment by Niba-nazar** [comment]
Hi,

I've tried including the suppliers in the configuration file, and I can query the data in "local, remote, and atc-local" modes without encountering any issues. But every time I changed anything in the config.ncl file, I had to restart the service.

**Comment by Niba-nazar** [comment]
Hi,

I've tried including the suppliers in the configuration file, and I can query the data in "local, remote, and atc-local" modes without encountering any issues. But every time I changed anything in the config.ncl file, I had to restart the service.

**Comment by Lilit0x** [comment]
Yes, that's because you can't update suppliers or anything through the config file, you have to do it through SQL queries.
Have you taken a look at the resource I linked up top?
