### ISSUE TITLE
Authentication Code Method Anomalies in Environment Credential Integration

### ISSUE THREAD

**Issue by Niba-nazar** [opsfolio/resource-surveillance#102]
Hi
I have tried IMAP surveilr ingest using both the device code and auth code methods. While the device code method worked smoothly, I also tested it with ngrok static domain and random domain configurations, all of which yielded the expected results. Below are the commands I used for reference

```bash
surveilr ingest imap -f="Inbox" --max-no-messages=12000 microsoft-365 -i="abxxxxxxxxx3c" -s="mbxxx~xxxxzURxxxx" -m auth-code -a " https://cb4d-202-83-55-151.ngrok-free.app"

surveilr ingest imap -f="Inbox" --max-no-messages=12000 microsoft-365 -i="abxxxxxxxxx3c" -s="mbxxx~xxxxzURxxxx" -m device-code
```

Still, adding credentials as an environment is not working as intended with the auth-code technique.
Getting error as below 

![image](https://github.com/opsfolio/resource-surveillance/assets/114569256/bb6fafd8-dc00-48d8-bc8e-1eaf1a6c993b)

The commands I tried with are as follows:

```bash
$ surveilr admin credentials microsoft-365 -i="abxxxxxxx" -s"mxxxxxxxx" -r="https://egret-nice-mink.ngrok-free.app" --env

$ surveilr admin credentials microsoft-365 -i="abxxxxxx" -s"mxxxxxxxxxxx" -r="https://egret-nice-mink.ngrok-free.app" --export | source

$ surveilr ingest imap -f="Inbox" --max-no-messages=12000 microsoft-365 -m auth-code
Microsoft 365 Oauth Server Listening on: http://127.0.0.1:8000

also tried like this too:
$ surveilr ingest imap microsoft-365 -m auth-code
```

We really appreciate your advice and help in getting this issue resolved.

**Comment by Lilit0x** [comment]
Hi @niba could you please try it out with the new v0.5.8, thanks.

**Comment by Niba-nazar** [comment]
Hi,
Tested IMAP functionality using version 0.5.9. Credential setup via environment variables is now functioning correctly. However, encountered a limitation with mail count capped at '1000'. Attempted to append '--max-no-messages=12000' to address this, but received the following error:

![image](https://github.com/opsfolio/resource-surveillance/assets/114569256/15ec1698-a18a-43b4-8819-4d7685d04048)

Need assistance resolving this issue.

**Comment by Lilit0x** [comment]
Hi there.
The `max-no-messages` argument has been replaced with `--batch-size` or `-b`. 
You could also have run `surveilr ingest imap --help` to get the list of all arguments.

**Comment by Niba-nazar** [comment]
Hi,
Thank you for the update. Despite attempting to utilize the ```--batch-size``` parameter, the mail count persists at its default value.
![image](https://github.com/opsfolio/resource-surveillance/assets/114569256/b1c38b4c-963d-4282-bd1a-c2b2ad106eeb)

**Comment by Lilit0x** [comment]
@Niba-nazar , please check the new release for the fix. v0.5.11.
Thanks

**Comment by rinshadka** [comment]
Working fine.
