### ISSUE TITLE
Introduce multi-device merging capability

### ISSUE THREAD

**Issue by shah** [opsfolio/resource-surveillance#11]
Add a new `surveilr admin merge --target new.db --db source1.db --db source2.db --db source3.db` capability which opens each source database, dumps its output, and merges the content into the `target` database.

- [ ] Implement `admin merge-sql --sqlite3 ...` as a generator for SQLite shell script that, when run, will do the work using an external `sqlite3` executable (the SQLite shell)
- [ ] support list of source databases locally available by generating filenames from passed-in arguments
- [ ] use globbing for source databases for locally available by discovering files and putting them into the generated script

Future possibilities:
- add `admin merge` capability without external `sqlite3` (may need to use external `sqlite3` since Rusqlite does not support `.dump`, [see this discussion](https://github.com/rusqlite/rusqlite/discussions/1210))
- support list of source databases remotely available (URLs, etc.)
- in case SQLite shell causes any issues try using DuckDB and its SQLite `ATTACH` and integration capabilities

**Comment by shah** [comment]
To merge multiple SQLite databases into a single database we use a script that is generated by `surveilr` that performs the following steps:

1. Use `surveilr admin init` to create an empty SQLite database with the proper table structures
2. Attach SQLite Databases: Use DuckDB's `ATTACH DATABASE` command to attach each source SQLite database file.
3. Insert Data from SQLite to DuckDB: Use `INSERT INTO ... SELECT ... FROM ...` queries to transfer data from each attached source SQLite database table into the attached target SQLite table.

To merge specific tables from three source SQLite databases (src1.sqlite.db, src2.sqlite.db, src3.sqlite.db) into a target database (target.sqlite.db), you can use the SQLite3 shell. Here's a script that demonstrates how to do this:

1. Use `surveilr admin init` to create an empty SQLite database with the proper table structures. Assume this is called the _Target database_.
2. Attach Source Databases: Use the `ATTACH DATABASE` command to attach each source database.
3. Insert Data into Target Database: Use `INSERT INTO ... SELECT ... FROM ...` queries to transfer data from the attached databases to the corresponding tables in the target database.

```sql
-- Attach the source databases
ATTACH 'src1.sqlite.db' AS src1;
ATTACH 'src2.sqlite.db' AS src2;
ATTACH 'src3.sqlite.db' AS src3;

-- Insert data from the 'device' table of each source database
INSERT INTO device SELECT * FROM src1.device;
INSERT INTO device SELECT * FROM src2.device;
INSERT INTO device SELECT * FROM src3.device;

-- Insert data from the 'ur_walk_session' table of each source database
INSERT INTO ur_walk_session SELECT * FROM src1.ur_walk_session;
INSERT INTO ur_walk_session SELECT * FROM src2.ur_walk_session;
INSERT INTO ur_walk_session SELECT * FROM src3.ur_walk_session;

-- Insert data from the 'ur_walk_session_path' table of each source database
INSERT INTO ur_walk_session_path SELECT * FROM src1.ur_walk_session_path;
INSERT INTO ur_walk_session_path SELECT * FROM src2.ur_walk_session_path;
INSERT INTO ur_walk_session_path SELECT * FROM src3.ur_walk_session_path;

-- Insert data from the 'uniform_resource' table of each source database
INSERT INTO uniform_resource SELECT * FROM src1.uniform_resource;
INSERT INTO uniform_resource SELECT * FROM src2.uniform_resource;
INSERT INTO uniform_resource SELECT * FROM src3.uniform_resource;

-- Insert data from the 'ur_walk_session_path_fs_entry' table of each source database
INSERT INTO ur_walk_session_path_fs_entry SELECT * FROM src1.ur_walk_session_path_fs_entry;
INSERT INTO ur_walk_session_path_fs_entry SELECT * FROM src2.ur_walk_session_path_fs_entry;
INSERT INTO ur_walk_session_path_fs_entry SELECT * FROM src3.ur_walk_session_path_fs_entry;

-- Detach source databases
DETACH DATABASE src1;
DETACH DATABASE src2;
DETACH DATABASE src3;
```

* Make sure the schema of these tables in the target database matches with the source databases.
* Ensure that the primary keys (ULIDs in your case) are unique across all databases to avoid any conflict during the merge.

Once this is proven we can just generate the SQLite code and execute it through `sqlite3` to do the merging. We can use this by calling something like this:

```bash
$ surveilr admin init -d target.sqlite.db -r && surveilr admin merge-sql --sqlite3 --db source1.db --db source2.db --db source3.db | sqlite3 target.sqlite.db
```

**Comment by shah** [comment]
@razakpm please try it out and let me know if it worked as designed. I am generating the SQL properly but I do not know if all the data is properly getting merged.

To generate the SQL use this strategy (you can provide as many `-d` globs as required).

```bash
$ surveilr admin merge-sql -d /one/*.db --d /two/**/*.db
```

**Comment by razakpm** [comment]
@shah it is tried and working fine. 
as we have dependency with sqlite3 that also need to mention in the document.
Verified surveilr in Linux and Windows.
