### ISSUE TITLE
Introduce Capturable Executables (`CE`s) resources

### ISSUE THREAD

**Issue by shah** [opsfolio/resource-surveillance#43]
When `fs-walk` command runs, pass in arguments or behaviors that allows certain patterns of files to be executed in a safe shell, and their STDOUT and STDERR captured and stored in `uniform_resource`. These scripts are referred to as _capturable executables_ or `CE`s and are influenced through _Processing Instructions_ (`PI`s) in file names. 

For example, if we want `fs-walk`, as it encounters a `abc.surveilr.sh` file to execute it, we can pass in `--capture_exec "surverilr[json]"` and it will execute the script, treat the output as JSON, and store it in `uniform_resource`. `surverilr[json]` becomes what is known as a Resource Surveillance _Processing Instruction_ (`PI`) and the pattern is arbitrary so long as the _nature_ is a named Rust reg ex capture group liked `surveilr\[(?P<nature>[^]]*)\]` (focus on `nature`, you can test this regular expressions at https://regex101.com/r/sVroiN/1).

The functionality we need:

- [x] Calls an executable without any parameters and assumes the output is whatever is in `[xyz]` PI as the `uniform_resource` _nature_.
- [x] If the filename is something like `myfile.surveilr-SQL.sh` it means that the output of the command will be treated as batch SQL and executed on the target SQLite database in the same transaction as the primary database. If we pass in everything through STDIN (see below), `INSERT INTO` should be easy.
- [x] Need to capture status code from the executable and STDERR from subprocess and pass it back so it can be stored in `walk_session_path_fs_entry`.`captured_executable` JSON column along with `args` and `stdin`.
- [x] Pass in the device, behavior, and other context information through CLI parameters or STDIN to the shell script. The input (STDIN) should look like this and contain a reasonably complete context so that executables know how to generate their output:

```json
{
  "surveilr-fs-walk": {
    "args": {
      "state_db_fs_path": "./e2e-test-state.sqlite.db"
    },
    "behavior": {
      "capturable_executables": [
        "surveilr\\[(?P<nature>[^\\]]*)\\]"
      ],
      "compute_digests": [".*"],
      "ignore_regexs": [
        "/(\\.git|node_modules)/",
      ],
      "ingest_content": [
        "\\.(md|mdx|html|json|jsonc|toml|yaml)$",
        "surveilr\\[(?P<nature>[^\\]]*)\\]"
      ],
      "root_paths": ["./support/test-fixtures"]
    },
    "device": { "device_id": "01HFHZGEZC763PWRBV2WKXBJH0" },
    "env": { "current_dir": "/home/snshah/workspaces/github.com/opsfolio/resource-surveillance" },
    "session": {
      "entry": {
        "path": "/home/snshah/workspaces/github.com/opsfolio/resource-surveillance/support/test-fixtures/echo-stdin.surveilr[json].sh"
      },
      "walk-path-id": "01HFHZGEZEDTW29BWWSEDE46WH",
      "walk-session-id": "01HFHZGEZD31S0V1EYBW4TT530"
    }
  }
}
```

**Comment by razakpm** [comment]
Here take the 'format' command as an example. We can use the following command:
```bash
npm run format -- -c
```
This command executes the 'format' script with Prettier to format all matched files of specified types. The expected STDOUT/STDERR output might look like this:
```bash
> react-code-quality-reference-project@0.0.1 format
> npx prettier --write "**/*.{js,jsx,ts,tsx}" -c

Checking formatting...
All matched files use Prettier code style!
```
In this context, the proposed enhancement would enable us to specify similar execution patterns for scripts during the fs-walk process, capturing and processing the resulting STDOUT and STDERR in a structured manner.

**Comment by shah** [comment]
@razakpm please try `v0.7.0` with the following test file:

```bash
#!/usr/bin/env bash

npm run format -- -c
```

You can name the file `npm-format.surveilr[txt].sh`, make sure to set executable permissions. You can see an example in `support/test-fixtures`. When the `fs-walk` command runs, it will encounter `npm-format.surveilr[txt].sh`, attempt to run it, and store its output as a `txt` uniform_resource. If there are any errors they will be in the row of `ur_walk_session_path_fs_entry` table's `ur_status` and `ur_diagnostics`.

**Comment by shah** [comment]
All initial features are now complete and `support/test-fixtures` contain examples:

* `capturable-executable.surveilr[json].sh` shows how to use a simple JSON output
* `echo-stdin.surveilr[json].sh` shows how to accept STDIN and emit JSON as STDOUT
* `idempotent.surveilr-SQL.sh` shows how a script can generate SQL and `surveilr` will execute the SQL as a batch in the same transaction (WARNING: SQL is unsanitized and this might be a security hole so be careful turning it on).

All the features are on by default but can be turned off:

* `surveilr fs-walk --captured-exec-sql` Regexp(s) control which files are considered capturable executables who output will be captured and executed as "SQL batch"
* `surveilr fs-walk --capture-exec` Regexp(s) control which files are considered capturable executables

**Comment by shah** [comment]
@razakpm and @rinshadka @ronikb now this new capability will allow us to run osQuery, Steampipe, CloudCN, and other tools on  workstations and other disconnected machines, store their output in SQLite, and share it using Syncthing. `surveilr` is now quite powerful as a complete to `udi-pgp-sqld`. Discuss with me if you're not sure why we might run osQuery through `surveilr`.
